# =============================================================================
# NexT Theme configuration
# =============================================================================
title: Vixuowis' Blog

avatar: /my-photo.jpeg

# Duoshuo
duoshuo_shortname: yinghuix

# Disqus
# disqus_shortname: yinghuix

language: zh-Hans

author: Vixuowis

description: 博客都是孤芳自赏，分享都是自我陶醉。

# Social links
social:
  GitHub: https://github.com/vixuowis
  Weibo: http://weibo.com/vixuowis
  ZhiHu: http://www.zhihu.com/people/vixuowis


# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
# google_site_verification: VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0


# Google Analytics
# Google分析ID
# google_analytics:


# 百度分析ID
# baidu_analytics: 50c15455e37f70aea674ff4a663eef27

# Specify the date when the site was setup
since: 2015
theme: next

feed:
  type: atom
  path: atom.xml
  limit: 20

# =============================================================================
# End NexT Theme configuration
# =============================================================================

###########landscape#############
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# # Site
# title: Yinghui's Blog
# subtitle: 所有的博客都是孤芳自赏，所有的分享都是自我陶醉。
# description:
# author: Vixuowis
# language:
# timezone:

# # URL
# ## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://yoursite.com
# root: /
# permalink: :year/:month/:day/:title/
# permalink_defaults:

# # Directory
# source_dir: source
# public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: downloads/code
# i18n_dir: :lang
# skip_render:

# # Writing
# new_post_name: :title.md # File name of new posts
# default_layout: post
# titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
# filename_case: 0
# render_drafts: false
# post_asset_folder: false
# relative_link: false
# future: true
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: true
#   tab_replace:

# # Category & Tag
# default_category: uncategorized
# category_map:
# tag_map:

# # Date / Time format
# ## Hexo uses Moment.js to parse and display date
# ## You can customize the date format as defined in
# ## http://momentjs.com/docs/#/displaying/format/
# date_format: YYYY-MM-DD
# time_format: HH:mm:ss

# # Pagination
# ## Set per_page to 0 to disable pagination
# per_page: 10
# pagination_dir: page

# # Extensions
# ## Plugins: http://hexo.io/plugins/
# ## Themes: http://hexo.io/themes/
# theme: landscape

# # Deployment
# ## Docs: http://hexo.io/docs/deployment.html
# deploy:
#   type: